---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - libxcb-xinerama0
      - libxcb-cursor0
      - zstd
    state: present

- name: Clean previous extraction directory
  become: true
  ansible.builtin.file:
    path: /tmp/anki
    state: absent

- name: Create directory
  ansible.builtin.file:
    path: /tmp/anki
    state: directory

- name: Download Anki tar file
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/ankitects/anki/releases/download/{{ anki.version }}/{{ anki.tar_version }}.tar.zst"
    dest: /tmp/anki.tar.zst

- name: Extract tar file
  become: true
  ansible.builtin.unarchive:
    src: /tmp/anki.tar.zst
    dest: /tmp/anki
    remote_src: true

- name: Run Anki install script
  become: true
  shell: "cd /tmp/anki/* && ./install.sh"

