---

- name: Install common desktop packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - meld # Diff / merge tool
    - xsel # to control windows
    - wmctrl # to control windows
    - xclip # to manipulate the clipboard
    - xdotool # to control windows