---
- name: Install Calibre system dependencies
  ansible.builtin.apt:
    name:
      - libopengl0
      - libegl1
      - libgl1
      - libxcb-cursor0
      - libxcb-xinerama0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-shape0
      - libxkbcommon-x11-0
      - libxkbcommon0
      - xdg-utils
    state: present


- name: Install Calibre eBook
  become: true
  ansible.builtin.shell: >
    wget --no-check-certificate -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin
  args:
    creates: /usr/bin/calibre

