- name: Run rust installation script
  shell: curl -sSf https://sh.rustup.rs | sh -s -- -y

- name: install treesitter
  shell: cargo install tree-sitter-cli
  become_user: nick

- name: install ripgrep
  shell: cargo install ripgrep
  become_user: nick

