- name: Run rust installation script
  shell: curl -sSf https://sh.rustup.rs | sh -s -- -y

- name: Install packages using cargo
  shell: cargo install {{ item }}
  become_user: nick
  loop:
    - tree-sitter-cli
    - ripgrep
    - aichat

