---
- name: Ubuntu desktop environment playbook
  hosts: localhost
  roles:
    # Common roles
    # - { role: locales, become: true }
     - { role: common, become: true }
     - { role: zsh, become: true }
    # - { role: dotfiles, become: true }
    # - { role: java-openjdk, become: true }
    # - { role: phantomjs, become: true }
    # - { role: projects-installer }
    # Server roles
    # - { role: apache2, become: true }
    # - { role: apache2-php, become: true }
    # - { role: beanstalkd, become: true }
    # - { role: blackfire, become: true }
    # - { role: composer, become: true }
     - role: githubixx.kubectl
       become: true
     - role: haxorof.docker_ce
       become: true
       docker_users:
         - nick
       docker_compose: true 
     - { role: gantsign.visual-studio-code, become: true }
     - role: gantsign.oh-my-zsh
       become: true 
       users:
         - username: nick
       plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-z
        - kubectl
       update_mode: auto
       write_zshrc: false
     - role: 0x0I.tmux
       become: true
    # - { role: elasticsearch, become: true }
    # - { role: exim, become: true }
    # - { role: fail2ban, become: true }
    # - { role: gvm, become: true }
    # - { role: hhvm, become: true }
    # - { role: mailcatcher, become: true }
    # - { role: mailhog, become: true }
    # - { role: memcached, become: true }
    # - { role: mysql57, become: true }
    # - { role: mysql56, become: true }
    # - { role: nginx, become: true }
    # - { role: nginx-php-fpm, become: true }
    # - { role: nodejs, become: true }
    # - { role: php, become: true }
    # - { role: php-pecl, become: true }
    # - { role: php-phar-tools, become: true }
     - { role: python, become: true }
    # - { role: redis, become: true }
    # - { role: rbenv, become: true }
     - { role: ssh, become: true }
    # Desktop roles
    # - { role: desktop, become: true }
    # - { role: desktop-cleanup, become: true }
    # - { role: desktop-autostart, become: true }
    # - { role: desktop-preferences-unity }
    # - { role: adapta-theme, become: true }
    # - { role: albert, become: true }
    # - { role: altyo, become: true }
    # - { role: arc-theme, become: true }
    # - { role: atom, become: true }
    # - { role: chromium, become: true }
    # - { role: claws-mail, become: true }
    # - { role: compton, become: true }
    # - { role: copyq, become: true }
    # - { role: dbeaver, become: true }
    # - { role: filezilla, become: true }
     - { role: firefox, become: true }
    # - { role: flatabulous, become: true }
    # - { role: gdrive, become: true }
    # - { role: geary, become: true }
    # - { role: gimp, become: true }
    # - { role: grub-customizer, become: true }
    # - { role: hubic, become: true }
    # - { role: indicator-sysmonitor, become: true }
    # - { role: ksuperkey, become: true }
    # - { role: libreoffice, become: true }
    # - { role: maim, become: true }
    # - { role: min, become: true }
    # - { role: mysql-workbench, become: true }
    # - { role: nautilus-plugins, become: true }
    # - { role: nemo, become: true }
    # - { role: notepadqq, become: true }
    # - { role: notify-osd, become: true }
    # - { role: qutebrowser, become: true }
    # - { role: remarkable, become: true }
    # - { role: remmina, become: true }
    # - { role: ripgrep, become: true }
    # - { role: rofi, become: true }
    # - { role: shutter, become: true }
    # - { role: sift, become: true }
    # - { role: slop, become: true }
    # - { role: skype, become: true }
    # - { role: smartgit, become: true }
    # - { role: spotify, become: true }
    # - { role: sublime3, become: true }
    # - { role: sunflower, become: true }
    # - { role: teamviewer, become: true }
     - { role: thunderbird, become: true }
    # - { role: ultra-flat-icons, become: true }
    # - { role: urxvt-perls }
    # - { role: vagrant, become: true }
    # - { role: virtualbox, become: true }
    # - { role: vokoscreen, become: true }
    # - { role: wine, become: true }
    # - { role: workrave, become: true }
    # - { role: xfce-dockbarx, become: true }
    # - { role: xmind, become: true }
    # bspwm
    # - { role: sxhkd, become: true }
    # - { role: bspwm, become: true }
    # - { role: bspwm-panel, become: true }
    # - { role: bspwm-environment, become: true }
    # User roles
    # - { role: gulp}
    # - { role: browsersync }
    # - { role: bower }
    # - { role: webpack }
  tasks:
    - name: copy git config
      copy: 
        src: dotfiles/.gitconfig
        dest: /home/nick/.gitconfig
      delegate_to: localhost
    - name: copy zsh config
      copy: 
        src: dotfiles/.zshrc
        dest: /home/nick/.zshrc
      delegate_to: localhost
    - name: add zsh plugins
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        owner: nick
        mode: '0755'
    - name: add zsh plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        owner: nick
        mode: '0755'
    - name: Touch secrets
      ansible.builtin.file:
        path: /home/nick/.secrets
        state: touch
        mode: u=rw,g=r,o=r
    - name: Create "docker" group
      become: true
      group:  
        name: "docker"
        state: present
    - name: Add remote "ubuntu" user to "docker" group
      become: true
      user:
        name: "nick"
        group: "docker"
        append: yes